# Notebook 4: Fit the Multi-level Random Slope and Intercept Model

# Data manipulation, transformation and visualisation
library(tidyverse)
# Nice tables
library(kableExtra)
# Simple features (a standardised way to encode vector data ie. points, lines, polygons)
#library(sf) 
# Spatial objects conversion
library(sp) 
# Thematic maps
library(tmap) 
# Colour palettes
library(viridis) 
# Fitting multilevel models
library(lme4)
# Tools for extracting information generated by lme4
library(merTools)
# Exportable regression tables
library(jtools)
# Spatial data manitulation
library(sf) 
getwd() 


# Read in the housing listings data
df1 <- read.csv('final_data_withsections.csv')


# Fit the mixed-effects model
mlm1 <- lmer(
  LogUNITPRICE ~ ROOMNUMBER + HASTERRACE + HASLIFT + HASAIRCONDITIONING + HASPARKINGSPACE + PARKINGSPACEPRICE +
    HASNORTHORIENTATION + HASSOUTHORIENTATION + HASEASTORIENTATION + HASWESTORIENTATION + HASBOXROOM +
    HASWARDROBE + HASSWIMMINGPOOL + HASDOORMAN + HASGARDEN + ISDUPLEX + ISSTUDIO + ISINTOPFLOOR + FLOORCLEAN +
    CADMAXBUILDINGFLOOR + CADDWELLINGCOUNT + CoolingDemandCategory + logincome + buildingdensity + benchdensity +
    greenareapercent + (1 + HASAIRCONDITIONING| CODBAR.1),
  data = df1
)

# Print the summary of the model
summary(mlm1)




library(MuMIn)
# Calculate R-squared
r2 <- r.squaredGLMM(mlm1)
print(r2)

# Calculate AIC
aic_value <- AIC(mlm1)
print(paste("AIC:", aic_value))

# Save the random slope values
re_m1 <- REsim(mlm1) %>% filter(groupFctr == "CODBAR.1") %>%
  filter(term == "HASAIRCONDITIONING")
str(re_m1)



# merge data with the shape file polygon for neighborhoods
bar_shp <- st_read("C:/Users/sggkenyo/Downloads/Barrios2021/Barrios_20210712.shp")
bar_shp2 <- merge(x = bar_shp, y = re_m1, by.x = "COD_DISBAR", by.y = "groupID")

# ensure geometry is valid
bar_shp2 = sf::st_make_valid(bar_shp2)

# create a map of the residuls
legend_title = expression("Neighbourhood-level residuals")

map_msoa = tm_shape(bar_shp2) +
  tm_fill(col = "median", title = legend_title, palette = magma(256, begin = 0, end = 1), style = "cont") + 
  tm_borders(col = "white", lwd = .01)  + 
  tm_compass(type = "arrow", position = c("right", "top") , size = 4) + 
  tm_scale_bar(breaks = c(0,1,2), text.size = 0.5, position =  c("center", "bottom")) 
map_msoa

# Export the residuals and final dataframe for further styling in ArcGIS
# Define the file path where you want to save the shapefile
output_file <- "C:/Users/sggkenyo/Documents/barrios_aircon_residuals2.shp"

# Save the sf object as a shapefile
st_write(bar_shp2, output_file, delete_dsn = TRUE)
